### ISSUE TITLE
Remove unneeded "express-subdomain" dependency

### ISSUE THREAD

**Issue by scowalt** [BandleCitySpacestation/bandlecity.space#4]
https://github.com/BandleCitySpacestation/bandlecity.space/blob/f6a95f8637867b9e0737dcd4c9660b329dcb629c/package.json#L41

**Comment by scowalt** [comment]
@danhsu47317 if you wanted to test/practice going through the Pull request / development flow this is a simple thing to start with

**Comment by danhsu47317** [comment]
@scowalt PR Created:
-https://github.com/BandleCitySpacestation/bandlecity.space/pull/5
